# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0004_warningconstraint")]

    operations = [
        migrations.AlterField(
            model_name="preorderposition",
            name="secret",
            field=models.CharField(db_index=True, max_length=254, unique=True),
        )
    ]
