# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0008_auto_20160207_1607")]

    operations = [
        migrations.RenameField(
            model_name="transactionpositionitem",
            old_name="product",
            new_name="position",
        )
    ]
