# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0009_auto_20160207_2045")]

    operations = [
        migrations.RemoveField(model_name="listconstraint", name="products"),
        migrations.RemoveField(model_name="warningconstraint", name="products"),
    ]
