# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-31 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_auto_20160828_1759"),
        ("core", "0018_productitem_is_visible"),
    ]

    operations = []
