# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-31 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0019_merge")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_backoffice_user",
            field=models.BooleanField(default=False),
        )
    ]
