# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-16 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0020_user_is_backoffice_user")]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="receipt_id",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        )
    ]
