# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-17 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0021_transaction_receipt_id")]

    operations = [
        migrations.AddField(
            model_name="listconstraint",
            name="confidential",
            field=models.BooleanField(default=False),
        )
    ]
