# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-10 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0026_auto_20161114_2240")]

    operations = [
        migrations.AddField(
            model_name="transactionposition",
            name="has_constraint_bypass",
            field=models.BooleanField(default=False),
        )
    ]
