# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-10 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_eventsettings_initialized"),
        ("core", "0027_transactionposition_has_constraint_bypass"),
    ]

    operations = []
