# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-15 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [("core", "0028_merge")]

    operations = [
        migrations.AlterModelManagers(
            name="cashdesksession",
            managers=[("active", django.db.models.manager.Manager())],
        ),
        migrations.AddField(
            model_name="product",
            name="import_source_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=180, null=True
            ),
        ),
    ]
