# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-17 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0030_ping")]

    operations = [
        migrations.AlterModelManagers(name="cashdesksession", managers=[]),
        migrations.AlterField(
            model_name="user",
            name="auth_token",
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
