# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-23 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0031_auto_20161217_2033")]

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=2500)),
                ("name", models.CharField(blank=True, max_length=40, null=True)),
                ("is_printable", models.BooleanField(default=True)),
            ],
        )
    ]
