# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-26 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0033_cashdesk_printer_handles_drawer")]

    operations = [
        migrations.AlterField(
            model_name="cashdesk",
            name="ip_address",
            field=models.GenericIPAddressField(verbose_name="IP address"),
        )
    ]
