# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-09 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0037_cashdeskdevice")]

    operations = [migrations.RemoveField(model_name="cashdesk", name="display_address")]
