# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0039_auto_20171217_1735")]

    operations = [
        migrations.AddField(
            model_name="preorderposition",
            name="information",
            field=models.CharField(blank=True, max_length=1000, null=True),
        )
    ]
