# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0040_preorderposition_information")]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_receipt",
            field=models.BooleanField(default=False),
        )
    ]
