# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-01 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0042_auto_20171225_0024")]

    operations = [
        migrations.AlterModelOptions(
            name="itemmovement", options={"ordering": ("timestamp",)}
        )
    ]
