# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-09 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0044_auto_20180609_2127")]

    operations = [
        migrations.AlterField(
            model_name="record", name="datetime", field=models.DateTimeField()
        )
    ]
