# Generated by Django 2.1.2 on 2018-11-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0048_auto_20181019_0012")]

    operations = [
        migrations.AddField(
            model_name="cashdesk",
            name="handles_items",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="cashdesk",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP-Adresse"
            ),
        ),
    ]
