# Generated by Django 2.1.3 on 2018-11-03 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0049_auto_20181103_1229")]

    operations = [
        migrations.AddField(
            model_name="record",
            name="cash_movement",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="record",
                to="core.CashMovement",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="closes_session",
            field=models.BooleanField(
                default=False,
                verbose_name="Report closes session and contains additional pages",
            ),
        ),
    ]
