# Generated by Django 2.1.3 on 2018-12-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0054_record_is_locked")]

    operations = [
        migrations.AddField(
            model_name="ping", name="synced", field=models.BooleanField(default=False)
        )
    ]
