# Generated by Django 2.1.11 on 2019-08-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20190819_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_admission',
            field=models.BooleanField(default=False),
        ),
    ]
