# Generated by Django 2.1.14 on 2019-12-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_product_is_admission"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsettings",
            name="last_import_questions",
            field=models.TextField(
                blank=True, default="", verbose_name="Last input for imported questions"
            ),
        ),
    ]
